# Generated by Django 5.0.1 on 2024-07-14 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0003_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
