# Generated by Django 5.0.1 on 2024-07-14 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0006_requests_user_alter_product_item_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requests',
            name='user',
        ),
    ]
